# Generated by Django 5.2.2 on 2025-06-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('installation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('nh3', models.FloatField()),
                ('ch4', models.FloatField()),
                ('co', models.FloatField()),
                ('battery_level', models.FloatField()),
                ('signal_strength', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='habil.sensor')),
            ],
            options={
                'verbose_name_plural': 'Raw Sensor Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_temperature', models.FloatField()),
                ('predicted_humidity', models.FloatField()),
                ('predicted_pm2_5', models.FloatField()),
                ('predicted_pm10', models.FloatField()),
                ('predicted_nh3', models.FloatField()),
                ('predicted_ch4', models.FloatField()),
                ('predicted_co', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='habil.sensor')),
            ],
            options={
                'verbose_name_plural': 'Predicted Values',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='AQIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aqi_value', models.FloatField()),
                ('aqi_category', models.CharField(max_length=50)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_data', to='habil.sensor')),
            ],
            options={
                'verbose_name_plural': 'AQI Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
