# Generated by Django 5.2.2 on 2025-06-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsensordata',
            name='no2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawsensordata',
            name='signal_strength',
            field=models.FloatField(),
        ),
    ]
