# Generated by Django 5.2.2 on 2025-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0002_rawsensordata_no2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('pollutant', models.CharField(max_length=10)),
                ('concentration', models.FloatField()),
                ('aqi_value', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('color_code', models.CharField(max_length=10)),
            ],
        ),
    ]
