# Generated by Django 5.2.2 on 2025-06-25 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0003_aqiresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictedvalues',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Predicted Values'},
        ),
        migrations.RemoveField(
            model_name='predictedvalues',
            name='prediction_date',
        ),
        migrations.AddField(
            model_name='predictedvalues',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
