# Generated by Django 5.2.2 on 2025-06-25 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0004_alter_predictedvalues_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedvalues',
            name='predicted_no2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
