# Generated by Django 5.2.2 on 2025-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0007_aqianalytics_pollutionforecast_pollutiontrend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqidata',
            name='aqi_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
