# Generated by Django 5.2.2 on 2025-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habil', '0009_alter_aqidata_aqi_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqiresult',
            name='aqi_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
